apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "smolkafka.fullname" . }}-scripts
  namespace: {{ .Release.Namespace }}
  labels: {{ include "smolkafka.labels" . | nindent 4 }}
data:
  config-init.sh: |
{{ .Files.Get "scripts/config-init.sh" | indent 4 }}
